Update target.yml

diff --git a/.github/workflows/target.yml b/.github/workflows/target.yml
--- a/.github/workflows/target.yml
+++ b/.github/workflows/target.yml
@@ -19,6 +19,28 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       # Use the output from the `check` step
+      - name: Run only if user has sufficient permissions
+        if: steps.check.outputs.has-permission
+        run: exit 0 #Successful
+      - name: Run only if user has NOT sufficient permissions
+        if: "! steps.check.outputs.has-permission"
+        run: exit 1 #Failed
+          
+
+
+  run-command:      
+    runs-on: ubuntu-latest
+    name: Run command
+    steps:
+      # Check for write permission
+      - name: Check user permission
+        id: check
+        uses: scherermichael-oss/action-has-permission@master
+        with:
+          required-permission: write
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          
       - name: Run label check
         if: steps.check.outputs.has-permission
         uses: HeatherComputer/.github/.github/workflows/target-label.yml@master
